### PR TITLE
Loading pizza

### PR DESCRIPTION
**Pull request by jakob-lj**
Could you review my very bad pizza?

### CODE REVIEW

**Comment by jakob-lj** [comment]
Will resolve issues

**Comment by haavardsjef** [comment]
Looks good! You might want to look into the "save without formatting" command in vscode next time 😄

**Comment by jakob-lj** [comment]
Actually, I manually formatted the documents

**Review by haavardsjef — CHANGES_REQUESTED** [review]
Good work! You still need to fix the merge issues

**Comment by jakob-lj** [comment]
@haavardsjef conflicts resolved. Could you please review once more?:)

**Pull request merged**
